templates/lambda-edge/.gitignore, templates/lambda-edge/README.md, templates/lambda-edge/package.json, templates/lambda-edge/src/index.ts
Here are the specific changes needed in the package.json file:
1. In the update script, add the --region us-east-1 option. This is necessary because Lambda@Edge functions must typically be deployed in the us-east-1 region.
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-at-the-edge.html
2. Add a new script called publish that uses aws lambda publish-version to create a new version of the Lambda function. Lambda@Edge requires you to deploy a specific version or an alias, so we need this step
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-edit-function.html
=> feat(lambda-edge): add bootstrap Lambda edge

templates/fastly/package.json
Fastly deploy commnad  need a package tar.gz.
But yarn build make only bin folder and wasm/js files. 
So I change the command from "deploy" to "publish".
"publish" command is " Build and deploy a Compute@Edge package to a Fastly service".
=> Patch fastly deploy command

templates/bun/tsconfig.json
The default `tsconfig.json` gives an error.
I tried adding a `jsxFactory` as the message suggest.
I conclude that `"jsx": "react-jsx"` already does the job for `jsxFactory` and `jsxFragmentFactory`. So I propose this change to remove it completely. Thank you.
=> fix(templates/bun): remove `jsxFragmentFactory` from tsconfig.json

templates/bun/tsconfig.json
Using Bun 1.0.2, `bun:*` import types seemed to be broken using the Bun preset.
Recreate:
`bun create hono@latest project-name`
Import any `bun` package in `src/index.ts` - `Cannot find module (x) or its corresponding type declarations.`
Quick check at [bun-types](https://github.com/oven-sh/bun-types), possibly missing `"types": ["bun-types"]` from `tsconfig.json`
Change attached, cheers
=> Add bun typings to templates/bun/tsconfig.json

templates/aws-lambda/package.json, templates/lambda-edge/package.json
[npm-run-all](https://github.com/mysticatea/npm-run-all) has not been maintained for 5 years and has some bugs.
- Signals are not handled correctly: https://github.com/mysticatea/npm-run-all/pull/171 was merged but not released
- Dependents are left out of date and reported having vulnerabilty: https://github.com/mysticatea/npm-run-all/issues/257
[npm-run-all2](https://github.com/bcomnes/npm-run-all2) is a simple fork of npm-run-all and addressed these issues.
=> migrate from npm-run-all to npm-run-all2

templates/fastly/build.js
Having fastly external allows you to import fastly modules as per the fastly documentation and gives you access to fastly:experimental.
=> Fastly should be external in esbuild.

templates/fastly/fastly.toml
After `npm create hono@latest` with picking fastly template, currently `fastly compute build` doesn't work (probably it's outdated). We can find the right build commands at https://github.com/fastly/compute-starter-kit-javascript-empty/blob/main/fastly.toml#L11-L12.
=> Fix build command in fastly.toml

templates/x-basic/package.json
when I create x-basic template and using pnpm,
cloudflare adapater from vite-dev-server in vite.config.ts is missing.
```ts
import adapter from "@hono/vite-dev-server/cloudflare";
```
it's fixed via installing vite-dev-server explicitly in package.json.
for avoiding same error, update template are welcome.
=> add @hono/vite-dev-server in package.json

templates/cloudflare-pages/tsconfig.json, templates/cloudflare-workers/tsconfig.json, templates/x-basic/tsconfig.json
I believe this change is necessary to get up-to-date TypeScript types for Cloudflare Workers.
From https://www.npmjs.com/package/@cloudflare/workers-types
> - @cloudflare/workers-types
>   The default entrypoint exposes the runtime types for a compatibility date **before** 2021-11-03.
...
> - @cloudflare/workers-types/2023-07-01
>   This entrypoint exposes the runtime types for a compatibility date **after** 2023-07-01.
I found this when I tried to use the `include` [R2ListOptions](https://developers.cloudflare.com/r2/api/workers/workers-api-reference/#r2listoptions) and got this TypeScript error:
> Object literal may only specify known properties, and 'include' does not exist in type 'R2ListOptions'.
To reproduce the error you can clone https://github.com/jldec/hono-latest-aug-7
There is …
=> Point to @cloudflare/workers-types/2023-07-01 from tsconfig.json

templates/cloudflare-workers/package.json, templates/cloudflare-workers/wrangler.toml
I encountered an issue while trying out Workers Builds with the template created by `npm create hono@latest my-app`, following the instructions in the [Hono documentation for Cloudflare Workers](https://hono.dev/docs/getting-started/cloudflare-workers). The current setup seems incompatible with Workers Builds, preventing the deployment process from functioning as expected.
This PR proposes the following changes to address the issue and ensure better compatibility with Workers Builds:
- **Add `main = "src/index.ts"` to `wrangler.toml`**: This ensures that the correct entry point is specified for the Worker script.
- **Update the deploy command in `package.json` to `"deploy": "wrangler deploy --minify"`**: This simplifies the deployment process by adding the `--minify` flag, which is …
=> Fix: Adjust configuration for Workers Builds compatibility in hono template

templates/cloudflare-workers/package.json, templates/cloudflare-workers/wrangler.toml
- Set observability.enabled to true
- Set head_sampling_rate to 1
Source: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
=> Enable observability for Cloudflare Worker logs

templates/nodejs/package.json, templates/nodejs/tsconfig.json
This PR will slightly update the package.json and the tsconfig.json to guide users into the right direction when scaffolding their Hono project with Node.js to align with Web standards as much as possible. The recommendation is taken from the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/modules/guides/choosing-compiler-options.html#im-compiling-and-running-the-outputs-in-nodejs).
The change in the package.json make sure that Node.js will interpret the package as an ES Module. The changes in the tsconfig.json accomplish several things:
- Reflect the Node.js lookup rules to determine whether a project follows ESM or CJS rules. Since we set `"type": "module"` in the package.json, the scaffolded project will follow the standardized ESM rules (plus `node_modules` support …
=> chore: update configs for modern node

templates/nodejs/src/index.ts
On many consoles, we can access the server with `ctrl + click` at URL.
Therefore, it is useful to have server info provided in the form of URL.
=> chore(nodejs): display the server url

templates/deno/.vscode/settings.json, templates/netlify/.vscode/settings.json
When a value is set for `deno.enablePaths`, the value of `deno.enable` is ignored.
=> Remove redundant `deno.enable` VS Code setting

.github/workflows/sync-branch.yml
This PR added a GitHub Actions script. The GitHub Actions script creates a branch synchronized with the version number of the `create-hono` package. If `create-hono` refers to the latest branch and retrieves the template, it will prevent breaking changes from being introduced by the combination of `create-hono` and the template.
=> feat: add GitHub Actions for "Sync versioned branch"

templates/nodejs/src/index.ts
Changes:
- define port inline for the serve command
- moved console.log into the second argument callback of `serve`
- utilise `info.address` and `info.port` to construct the URL
=> fix(nodejs): move console.log inside callback

templates/cloudflare-workers+vite/.gitignore, templates/cloudflare-workers+vite/README.md, templates/cloudflare-workers+vite/package.json, templates/cloudflare-workers+vite/public/static/style.css, templates/cloudflare-workers+vite/src/index.tsx, templates/cloudflare-workers+vite/src/renderer.tsx, templates/cloudflare-workers+vite/tsconfig.json, templates/cloudflare-workers+vite/vite.config.ts, templates/cloudflare-workers+vite/wrangler.jsonc, templates/cloudflare-workers/package.json, templates/x-basic/package.json
This PR introduces a new template for Cloudflare Workers who are using Vite and [@cloudflare/vite-plugin](https://github.com/cloudflare/workers-sdk/tree/main/packages/vite-plugin-cloudflare). The `@cloudflare/vite-plugin` can emulate the Cloudflare environment as the same way as Wrangler. So it's better than using `@hono/vite-dev-server` for Cloudflare Workers.
Plus, Cloudflare will recommend using Cloudflare Workers instead of Cloudflare Pages for full-stack applications since both will be unified and encourage users to use Workers. So, we plan to make the `cloudflare-pages` obsolete and use this `cloudflare-workers+vite` template instead of that.
=> feat: add `cloudflare-workers+vite` template

templates/cloudflare-pages/README.md, templates/cloudflare-pages/package.json, templates/cloudflare-pages/tsconfig.json, templates/cloudflare-workers+vite/README.md, templates/cloudflare-workers+vite/package.json, templates/cloudflare-workers+vite/tsconfig.json, templates/cloudflare-workers/README.md, templates/cloudflare-workers/package.json, templates/cloudflare-workers/tsconfig.json
This pull request apply recommended migration for worker types usage for `wrangler@4.x`
- Remove `@cloudflare/workers-types`
- Add indication to user `npx wrangler types` command in order to generate cloudflare and worker binding types 
- https://developers.cloudflare.com/workers/wrangler/commands/#types
- https://developers.cloudflare.com/workers/languages/typescript/#1-uninstall-cloudflareworkers-types
=> Update cloudflare templates in order to follow wrangler v4 types migration

templates/nodejs/package.json, templates/nodejs/tsconfig.json
Fixing nodejs starter instead of adding a Google Cloud Run starter as discussed in #92
=> make nodejs starter ready-to-use

templates/fastly/src/index.ts
`app.fire()` is deprecated, so use `hono/service-worker`'s `fire()`.
https://hono.dev/docs/api/hono#fire
=> use `fire()` from `hono/service-worker` instead of `app.fire()`
